### ISSUE TITLE
8장 단순 오타? 제보드립니다 ㅎㅎ

### ISSUE THREAD

**Issue by 3Cat-jaguar** [GaepoMorningEagles/mini_raytracing_in_c#10]
마지막에 Code21 : [miniRT/src/trace/ray/phong_lighting.c]
에서 return 하는 값에 ambient 가 scene->ambient 일 것 같아서요
다른데서도 이런 단순 오타들을 발견했는데 이슈에 제보할 수 있는걸 이제야 알았네요;;
이해하기 어려운건 아니지만 고치면 좋을 오타들 발견하면 여기로 제보드리면 될까요???
이런 좋은 자료 만들어주셔서 감사합니다 ㅠㅠㅠ 세 분 덕분에 미니알티를 쉽게 재밌게 따라가고있어요 ㅠㅠㅠㅠ 영어인데다 c++ 로 된 그 자료를 보며... 힘들었던 과거여 안녕...

**Comment by hyongti** [comment]
앗 감사합니다 !!
Code21 : [miniRT/src/trace/ray/phong_lighting.c]
의
return (vmult(vplus(vplus(ambient, diffuse), specular), brightness));
 에서
return (vmult(vplus(diffuse, specular), brightness)); 
로 수정하겠습니다! 

ambient는 Code16: [miniRT/src/trace/ray/phong_lighting.c]에서 맨 마지막에 한번만 더하면 됩니다! 

수정 필요한 부분 있으면 언제든 남겨주세요 ㅎㅎ

**Comment by Likilee** [comment]
@hyongti 님 수정 중 이신건가욤??

**Comment by hyongti** [comment]
@Likilee 수정 끝났는데 이슈 닫는 버튼이 없어용 ㅠ_ㅠ

**Comment by Likilee** [comment]
@hyongti  닫을게용 ><
