### ISSUE TITLE
[08.md 오타수정 재요청 & 09.md 질문]

### ISSUE THREAD

**Issue by Hyoj-Kim** [GaepoMorningEagles/mini_raytracing_in_c#11]
우선 miniRT를 시작하기 전에 막막함을 해소시켜주는 좋은 교재 만들어주셔서 정말 감사합니다!
이론을 공부해봐도 이걸 코드로 어떻게 옮겨야하나 싶었는데, 하나씩 따라해보며 개념으로만 익힌 것을 눈으로 보니까 이렇게 즐거운 과제의 시작이 있었나 싶을 정도로 재밌게 공부하고 있습니다ㅎㅎ

> 8.4. 챕터에서 ‘교점에 도달한 빛 = Ambient + Σ(Specular + Diffuse)’ 라고 설명해주셨고, code13의 phong_lighting()도 그에 맞게 작성되어있습니다. 뒤에 Σ부분인 point_light_get()함수도  code19까지는 이 공식에 맞추어 작성되어있구요.
> 
> 
> 그런데 8.4.4. code21의 point_light_get()에서는 ambient가 추가되었습니다. 
> 이 경우 ‘교점에 도달한 빛 = Σ(Ambient + Specular + Diffuse)’가 되는데, 중간에 바뀌게 된 이유가 따로 있을까요?? 
> 사실 ambient값이 충분히 작은 값이자 상수라서 더 해지는 위치가 큰 영향을 미칠 것 같지는 않지만 바뀐 이유가 궁금합니다.
> 
> 참고하셨다고 한 learn OpenGL을 쭉 살펴보니 multiple lights에서는 광원마다 이 세 개의 요소를 전부 더해주고 있어서 후반부에 수정하신 것 같기도 하네요(?)
> 

closed 된 이슈 확인해보니 이전에 이미 제보된 내용이었군요...! 하지만 아직 제대로 반영되지 않은 것 같아서 다시 요청드립니다.
(어떻게 보면 사소한 부분인데 괜히 꽂혀서 한동안 고민했던지라...ㅎ)

대신 추가로 오타 제보합니다! [8.4. 챕터](https://github.com/GaepoMorningEagles/mini_raytracing_in_c/blob/main/08.phong_lighting.md#84-phong-lighting-model) ‘교점에 도달한 빛 = Ambinet + Σ(Specular + Diffuse)’ 에서 Ambient 오타있습니다.

---

9.3 챕터 code2에서 

```c
light_dir = vminus(light->origin, scene->rec.p);
light_len = vlength(light_dir);
light_ray = ray(vplus(scene->rec.p, vmult(scene->rec.normal, EPSILON)), light_dir);
```

light_ray = p + ⍷n  라고 작성해주셨는데, 여기서 EPSILON이 등장하는 이유가 컴퓨터의 연산으로는 소수점에서 오차가 발생해 픽셀이 깨지는 경우가 발생하기 때문이라고 알고 있습니다. 

이 문제를 해결하기 위해 광원 방향으로 교차점에서 광원 방향으로 살짝 띄운 위치에서 그림자 ray를 쏘는 것으로 생각했는데, 위의 코드에서는 교차점의 normal 방향으로 띄우게 작성되어 있어서 이런 근사를 사용하신 이유가 궁금합니다!

개인적으로는 scene→rec.normal을 light_dir(단, light_len 계산 후에 light_dir을 unit으로 바꿔줄 것)으로 바꾸는 것이 보다 명확한 근사라고 생각했습니다. 따라서 저는 아래와 같이 수정해서 사용하고 있습니다.

```c
light_dir = vminus_(light->origin, scene->rec.p);
light_len = vlength(light_dir);
light_dir = vunit(light_dir);
light_ray = ray(vplus_(scene->rec.p, vmult(light_dir, EPSILON)), light_dir);
...
// 후반부에 등장하는 vunit은 삭제
```

**Comment by Likilee** [comment]
와웅 디테일한 이슈 제안 감사드립니당. 빠른 시일내로 검토 후 적용하겠습니다 :)

**Comment by Likilee** [comment]
빠른 시일내의 검토가 약 2년이 지났습니다 ㅜㅜ 
말씀해주신 8챕터 오기, 오타 모두 수정했습니다 :) 
감사합니다!! 

9챕터 말씀해주신 EPSILON계산에 대해서는, 여전히 저는 교차점의 법선방향으로 살짝 띄운 위치가 맞다고 판단됩니다. 그 이유는
'소수점에서 오차가 발생해 픽셀이 깨지는 경우'의 원인이, 교차점 자신이 그림자 ray와의 교점이 되어 그림자를 발생시키는 상황 이라고 판단했고, 개념적으로 교차점의 법선방향으로 '띄워주는' 것이 맞지 않나 생각됩니다.
