### ISSUE TITLE
[02.vector.md] 본문 수정 제안

### ISSUE THREAD

**Issue by owel-dev** [GaepoMorningEagles/mini_raytracing_in_c#6]
[02.vector.md]
2.2목차의 main.c 코드 같은 경우

주석을 이용하여
이전 챕터의 main.c파일의 내용에서 
제거된 부분과 추가된 부분을 표시해 주셨는데

처음 보는 독자 입장에서는 "읭?"하고 헷갈리는 부분이 있을수도 있을 것 같아서요.
또, 제거된 코드가 들어가 내용이 길어지는 부분도 있는 것 같고 
따로 주석으로 표시해주지 않으셔도 읽는데 무리가 없을 것 같다는 생각이 들어서

1. 아예 표시하지 않거나 
2. 추가된 부분만
```
// 추가된 부분 ↓ 
```
같은 식으로 표시하면 어떨까 싶어 제안 드립니다.

추가로,
본문의 canvas_height 변수 초기화하는 부분이 누락되어 있습니다.

**Comment by Likilee** [comment]
이슈 확인했습니다 ulee님 ㅎㅎ 
1. 코드 영역 가독성 개선 논의 후 수정 해보겠습니다!
감사합니다 :)
